#ifndef SL_AGENT_PROTOCOL_H
#define SL_AGENT_PROTOCOL_H
enum AgentProtocol{
	CLIENT_MSG_LOGIN_REQ = 1,
	CLIENT_MSG_SELECT_ROLE_REQ = 2,
	CLIENT_MSG_CREATE_ROLE_REQ = 3,


	SERVER_MSG_LOGIN_RSP = 100000,
	SERVER_MSG_SELECT_ROLE_RSP = 100001,
	SERVER_MSG_CREATE_ROLE_RSP = 100002,
};

enum ProtocolError{
	ERROR_NO_ERROR = 0,
	ERROR_ACCOUNT_AUTHEN_FAILED = 1,
	ERROR_GET_ROLE_LIST_FAILED = 2,
	ERROR_DISTRIBUTE_LOGIC_FAILED = 3,
	ERROR_LOAD_PLAYER_FAILED = 4,
	ERROR_TOO_MUCH_ROLE = 5,
	ERROR_CREATE_ROLE_FAILED = 6,

};
#endif