#ifndef SL_NODE_PROTOCOL_H
#define SL_NODE_PROTOCOL_H
enum NodeProtocol{
	ASK_FOR_ALLOC_ID_AREA = 1,
	GIVE_ID_AREA = 2,
	
	MASTER_MSG_START_NODE = 20,
	MASTER_MSG_NEW_NODE = 21,
	
	
	CLUSTER_MSG_NEW_NODE_COMING = 100,

	GATE_MSG_TRANSMIT_MSG_TO_LOGIC = 200,
};
#endif