#ifndef SL_NODE_PROTOCOL_H
#define SL_NODE_PROTOCOL_H
enum NodeProtocol{
	ASK_FOR_ALLOC_ID_AREA = 1,
	GIVE_ID_AREA = 2,
	DB_COMMAND_EXECUTE = 3,
	MASTER_MSG_START_NODE = 4,
	MASTER_MSG_NEW_NODE = 5,
	CLUSTER_MSG_NEW_NODE_COMING = 6,
	GATE_MSG_TRANSMIT_MSG_TO_LOGIC = 7,
	NODE_CAPACITY_LOAD_REPORT =8,

};
#endif