// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolID.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ProtocolID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* ClientMsgID_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ServerMsgID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ProtocolID_2eproto() {
  protobuf_AddDesc_ProtocolID_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ProtocolID.proto");
  GOOGLE_CHECK(file != NULL);
  ClientMsgID_descriptor_ = file->enum_type(0);
  ServerMsgID_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ProtocolID_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_ProtocolID_2eproto() {
}

void protobuf_AddDesc_ProtocolID_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ProtocolID.proto*j\n\013ClientMsgID\022\031\n\024CLI"
    "ENT_MSG_LOGIN_REQ\020\350\007\022\037\n\032CLIENT_MSG_SELEC"
    "T_ROLE_REQ\020\351\007\022\037\n\032CLIENT_MSG_CREATE_ROLE_"
    "REQ\020\352\007*m\n\013ServerMsgID\022\032\n\024SERVER_MSG_LOGI"
    "N_RSP\020\240\215\006\022 \n\032SERVER_MSG_SELECT_ROLE_RSP\020"
    "\241\215\006\022 \n\032SERVER_MSG_CREATE_ROLE_RSP\020\242\215\006", 237);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ProtocolID.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ProtocolID_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ProtocolID_2eproto {
  StaticDescriptorInitializer_ProtocolID_2eproto() {
    protobuf_AddDesc_ProtocolID_2eproto();
  }
} static_descriptor_initializer_ProtocolID_2eproto_;
const ::google::protobuf::EnumDescriptor* ClientMsgID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientMsgID_descriptor_;
}
bool ClientMsgID_IsValid(int value) {
  switch(value) {
    case 1000:
    case 1001:
    case 1002:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ServerMsgID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ServerMsgID_descriptor_;
}
bool ServerMsgID_IsValid(int value) {
  switch(value) {
    case 100000:
    case 100001:
    case 100002:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
