//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ProtocolID.proto
namespace ProtocolID
{
    [global::ProtoBuf.ProtoContract(Name=@"ClientMsgID")]
    public enum ClientMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_LOGIN_REQ", Value=1000)]
      CLIENT_MSG_LOGIN_REQ = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_SELECT_ROLE_REQ", Value=1001)]
      CLIENT_MSG_SELECT_ROLE_REQ = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_CREATE_ROLE_REQ", Value=1002)]
      CLIENT_MSG_CREATE_ROLE_REQ = 1002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServerMsgID")]
    public enum ServerMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MSG_LOGIN_RSP", Value=100000)]
      SERVER_MSG_LOGIN_RSP = 100000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MSG_SELECT_ROLE_RSP", Value=100001)]
      SERVER_MSG_SELECT_ROLE_RSP = 100001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MSG_CREATE_ROLE_RSP", Value=100002)]
      SERVER_MSG_CREATE_ROLE_RSP = 100002
    }
  
}