//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Protocol.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"AttribType")]
    public enum AttribType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_INVAILED", Value=0)]
      DTYPE_INVAILED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_INT8", Value=1)]
      DTYPE_INT8 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_INT16", Value=2)]
      DTYPE_INT16 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_INT32", Value=3)]
      DTYPE_INT32 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_INT64", Value=4)]
      DTYPE_INT64 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_STRING", Value=5)]
      DTYPE_STRING = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_FLOAT", Value=6)]
      DTYPE_FLOAT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_STRUCT", Value=7)]
      DTYPE_STRUCT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DTYPE_BLOB", Value=8)]
      DTYPE_BLOB = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_NO_ERROR", Value=0)]
      ERROR_NO_ERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_ACCOUNT_AUTHEN_FAILED", Value=1)]
      ERROR_ACCOUNT_AUTHEN_FAILED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_GET_ROLE_LIST_FAILED", Value=2)]
      ERROR_GET_ROLE_LIST_FAILED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_DISTRIBUTE_LOGIC_FAILED", Value=3)]
      ERROR_DISTRIBUTE_LOGIC_FAILED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_LOAD_PLAYER_FAILED", Value=4)]
      ERROR_LOAD_PLAYER_FAILED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_TOO_MUCH_ROLE", Value=5)]
      ERROR_TOO_MUCH_ROLE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CREATE_ROLE_FAILED", Value=6)]
      ERROR_CREATE_ROLE_FAILED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_SYSTEM_ERROR", Value=7)]
      ERROR_SYSTEM_ERROR = 7
    }
  
}